# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
