# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0004_auto_20160506_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hacker_news.New'),
        ),
    ]
