# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0005_auto_20160506_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
