# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0006_new_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 7, 16, 7, 12, 827001)),
            preserve_default=False,
        ),
    ]
