# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0007_new_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_link',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hacker_news.comment'),
            preserve_default=False,
        ),
    ]
